application: wikihouse-cc
version: timelapse
runtime: python27
api_version: 1
threadsafe: true

builtins:
#- datastore_admin: on

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: static/src/favicon.ico
  upload: static/src/favicon.ico
  expiration: 7d

- url: /robots.txt
  static_files: static/src/robots.txt
  upload: static/src/robots.txt
  expiration: 7d

- url: /static
  static_dir: static/build
  expiration: 7d

- url: /blob/.*
  script: blob.app

- url: /admin/*
  script: main.app
  login: required

- url: .*
  script: main.app

